# -*- coding: utf-8 -*-
"""AST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rJZP19dOhqDsRnQQ9IK9h9a-pDu98I7
"""

import ast
import sys
import os
import glob
import tempfile
from git import Repo
from neo4j import GraphDatabase
def generate_ast(code_string):
    """
    Generates the Abstract Syntax Tree (AST) for the given code string.

    Args:
        code_string (str): A string containing Python code.

    Returns:
        ast.AST or None: The AST object if parsing is successful, otherwise None.
    """
    try:
        ast_tree = ast.parse(code_string)
        return ast_tree
    except SyntaxError as e:
        print(f"Syntax error: {e}", file=sys.stderr)
        return None

def generate_asts_from_dir(directory):
    """
    A generator that yields (relative_path, ast_tree) for each .py file in the directory.

    Args:
        directory (str): The directory to search for .py files.

    Yields:
        tuple: (relative_path, ast_tree) where relative_path is the path relative to the directory,
               and ast_tree is the AST object.
    """
    for py_file in glob.glob(os.path.join(directory, '**', '*.py'), recursive=True):
        relative_path = os.path.relpath(py_file, directory)
        with open(py_file, 'r') as f:
            try:
                code = f.read()
            except:
                print(f"Error with file {relative_path}")
        ast_tree = generate_ast(code)
        if ast_tree is not None:
            yield (relative_path, ast_tree)


class ASTGraphBuilder(ast.NodeVisitor):
    """
    Traverses an AST and builds a Knowledge Graph in Neo4j.
    """

    def __init__(self, driver, file_path):
        self.driver = driver
        self.file_path = file_path
        self.current_parent_id = None
        self.node_counter = 0

    def generic_visit(self, node):
        # Create a node in Neo4j for the current AST node
        node_id = self.node_counter
        self.node_counter += 1

        with self.driver.session() as session:
            # Create the AST node
            session.run(
                "CREATE (n:ASTNode {id: $id, type: $type})",
                id=node_id,
                type=type(node).__name__
            )

            # If this is the first node (root), link it to the file
            if self.current_parent_id is None:
                session.run(
                    """
                    MATCH (f:File {path: $path})
                    CREATE (f)-[:CONTAINS]->(n:ASTNode {id: $id})
                    """,
                    path=self.file_path,
                    id=node_id
                )
            else:
                # Link to parent
                session.run(
                    """
                    MATCH (parent:ASTNode {id: $parent_id})
                    MATCH (child:ASTNode {id: $child_id})
                    CREATE (parent)-[:CHILD_OF]->(child)
                    """,
                    parent_id=self.current_parent_id,
                    child_id=node_id
                )

        # Update parent ID for children
        old_parent_id = self.current_parent_id
        self.current_parent_id = node_id

        # Visit children
        for field, value in ast.iter_fields(node):
            if isinstance(value, list):
                for item in value:
                    if isinstance(item, ast.AST):
                        self.visit(item)
            elif isinstance(value, ast.AST):
                self.visit(value)

        # Restore parent ID after visiting children
        self.current_parent_id = old_parent_id


def init_graph(driver, file_path):
    """
    Initializes a File node in the graph.
    """
    with driver.session() as session:
        session.run(
            "CREATE (f:File {path: $path})",
            path=file_path
        )


if __name__ == "__main__":
    # Check for correct command-line argument
    if len(sys.argv) != 2:
        print("Usage: python script.py <repo_url>")
        sys.exit(1)

    # Get the repository URL from command-line argument
    repo_url = sys.argv[1]

    # Setup Neo4j connection
    driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "testpassword123"))

    # Use a temporary directory that gets cleaned up automatically
    with tempfile.TemporaryDirectory() as temp_dir:
        print(f"Cloning repository to {temp_dir}")
        Repo.clone_from(repo_url, temp_dir)

        # Process each Python file
        for relative_path, ast_tree in generate_asts_from_dir(temp_dir):
            print(f"Processing {relative_path}...")
            # Initialize file node
            init_graph(driver, relative_path)

            # Build the graph for this AST
            builder = ASTGraphBuilder(driver, relative_path)
            builder.visit(ast_tree)

    # Close the Neo4j driver
    driver.close()